# Generated by Django 5.1.1 on 2024-10-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('game_code', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syntax_highlighting', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('none', 'None')], default='python', max_length=20)),
                ('author', models.CharField(default='Unknown Author', max_length=255)),
                ('num_categories', models.IntegerField()),
                ('words_per_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('explanation', models.TextField(default='No explanation provided')),
                ('related_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='connections_app.connectionsgame')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesses', models.JSONField()),
                ('time_taken', models.JSONField()),
                ('is_won', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections_app.connectionsgame')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='connections_app.category')),
            ],
        ),
    ]
