# Generated by Django 5.1.1 on 2024-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsgame',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('connections_games', models.ManyToManyField(related_name='courses', to='connections_app.connectionsgame')),
            ],
        ),
    ]
