# Generated by Django 5.1.1 on 2024-11-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0002_connectionsgame_published_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='connections_games',
        ),
        migrations.AddField(
            model_name='connectionsgame',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='connections_app.course'),
        ),
    ]
