# Generated by Django 5.1.1 on 2024-11-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0003_remove_course_connections_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsgame',
            name='relevant_info',
            field=models.TextField(default=''),
        ),
    ]
