# Generated by Django 5.1.1 on 2025-02-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections_app', '0005_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsgame',
            name='max_mistakes',
            field=models.IntegerField(default=4),
        ),
    ]
